{% set name = "radon" %}
{% set version = "2.2.0" %}
{% set sha256 = "d5b7fd86c8ce3f81a2307298aa5e00a0b9d3334c9aeb69a9edce654b302cf81d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - radon = radon:main

requirements:
  build:
    - python
    - setuptools
  run:
    - mando
    - colorama >=0.3
    - flake8-polyfill
    - python

test:
  imports:
    - radon
  commands:
    - radon

about:
  home: https://github.com/rubik/radon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Code Metrics in Python'

  description: |
    Radon is a Python tool that computes various metrics from the source code. Radon can compute:
    
    - McCabe’s complexity, i.e. cyclomatic complexity
    - raw metrics (these include SLOC, comment lines, blank lines, &c.)
    - Halstead metrics (all of them)
    - Maintainability Index (the one used in Visual Studio)

extra:
  recipe-maintainers:
    - igortg
