{% set version = "4.2.0" %}

package:
  name: radon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/radon/radon-{{ version }}.tar.gz
  sha256: b73f6f469c15c9616e0f7ce12080a9ecdee9f2335bdbb5ccea1f2bae26e8d20d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - radon = radon:main

requirements:
  build:
    - python
    - pip
  run:
    - mando
    - colorama >=0.3
    - flake8-polyfill
    - python

test:
  imports:
    - radon
  commands:
    - radon

about:
  home: https://github.com/rubik/radon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Code Metrics in Python
  description: |
    Radon is a Python tool that computes various metrics from the source code. Radon can compute:

    - McCabe’s complexity, i.e. cyclomatic complexity
    - raw metrics (these include SLOC, comment lines, blank lines, &c.)
    - Halstead metrics (all of them)
    - Maintainability Index (the one used in Visual Studio)
  doc_url: https://radon.readthedocs.io

extra:
  recipe-maintainers:
    - igortg
    - tonybaloney
